### ISSUE TITLE
where can I found requirements?

### ISSUE THREAD

**Issue by kura6789** [Nomade040/csgo-derank#1]
like what should I pip install...

**Comment by kura6789** [comment]
I did that but i have few  questions. Have u got discord? Can u help me, please?

**Comment by Nomade040** [comment]
Sorry, I just saw your question now. I added the list of modules used by Deranker to the wiki page. BTW I am refactoring the code into C++ and it will be released in 2 days max so Python will be discontinued(but the latest version of the Python release is working pretty well).

My discord: Nomade#2165

**Comment by kura6789** [comment]
Accept me on discord, thanks for your work :)

**Comment by Nomade040** [comment]
I just accepted it. Thanks :)
